"""initial database schema

Revision ID: 8313b7d8ba8a
Revises: 
Create Date: 2026-09-28 16:39:46.619262
"""
from typing import Sequence, Union
from decimal import Decimal

from alembic import op
import sqlalchemy as sa



revision: str = '8313b7d8ba8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('emission_factors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('factor_value', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('factor_unit', sa.String(length=100), nullable=False),
    sa.Column('co2e_unit', sa.String(length=32), server_default='kg_co2e', nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('factor_value >= 0', name='ck_emission_factors_non_negative_value'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=False),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('emission_factor_id', sa.UUID(), nullable=False),
    sa.Column('calculated_co2e', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('calculated_co2e >= 0', name='ck_activities_non_negative_calculated_co2e'),
    sa.CheckConstraint('quantity >= 0', name='ck_activities_non_negative_quantity'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['emission_factor_id'], ['emission_factors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activities_activity_date', 'activities', ['activity_date'], unique=False)
    op.create_index('ix_activities_category_id', 'activities', ['category_id'], unique=False)
    op.create_index('ix_activities_emission_factor_id', 'activities', ['emission_factor_id'], unique=False)
    op.create_index('ix_activities_user_id', 'activities', ['user_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('baseline_co2e', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('target_co2e', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_goals_user_id', 'goals', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)

    categories = sa.table(
        'categories',
        sa.column('name', sa.String(length=100)),
        sa.column('description', sa.String(length=500)),
        sa.column('is_active', sa.Boolean()),
    )
    op.bulk_insert(
        categories,
        [
            {'name': 'Transport', 'description': 'Development category seed', 'is_active': True},
            {'name': 'Energy', 'description': 'Development category seed', 'is_active': True},
            {'name': 'Food', 'description': 'Development category seed', 'is_active': True},
            {'name': 'Travel', 'description': 'Development category seed', 'is_active': True},
            {'name': 'Waste', 'description': 'Development category seed', 'is_active': True},
            {'name': 'Purchases', 'description': 'Development category seed', 'is_active': True},
        ],
    )

    emission_factors = sa.table(
        'emission_factors',
        sa.column('category', sa.String(length=100)),
        sa.column('activity_type', sa.String(length=100)),
        sa.column('factor_value', sa.Numeric(precision=20, scale=10)),
        sa.column('factor_unit', sa.String(length=100)),
        sa.column('co2e_unit', sa.String(length=32)),
        sa.column('source_name', sa.String(length=255)),
        sa.column('source_year', sa.Integer()),
        sa.column('region', sa.String(length=100)),
        sa.column('is_active', sa.Boolean()),
    )
    development_source = 'EcoTrack DEV ONLY placeholder; not a real-world factor'
    op.bulk_insert(
        emission_factors,
        [
            {
                'category': 'Transport',
                'activity_type': 'car_petrol',
                'factor_value': Decimal('1.0000000000'),
                'factor_unit': 'kg_co2e_per_test_unit',
                'co2e_unit': 'kg_co2e',
                'source_name': development_source,
                'source_year': 2026,
                'region': 'DEV ONLY - not production data',
                'is_active': True,
            },
            {
                'category': 'Energy',
                'activity_type': 'electricity',
                'factor_value': Decimal('1.0000000000'),
                'factor_unit': 'kg_co2e_per_test_unit',
                'co2e_unit': 'kg_co2e',
                'source_name': development_source,
                'source_year': 2026,
                'region': 'DEV ONLY - not production data',
                'is_active': True,
            },
            {
                'category': 'Food',
                'activity_type': 'meat',
                'factor_value': Decimal('1.0000000000'),
                'factor_unit': 'kg_co2e_per_test_unit',
                'co2e_unit': 'kg_co2e',
                'source_name': development_source,
                'source_year': 2026,
                'region': 'DEV ONLY - not production data',
                'is_active': True,
            },
        ],
    )

    op.execute(
        """
        CREATE FUNCTION prevent_emission_factor_rewrite() RETURNS trigger AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                RAISE EXCEPTION 'Emission factors are immutable; deactivate instead';
            END IF;
            IF ROW(
                NEW.id, NEW.created_at, NEW.category, NEW.activity_type, NEW.factor_value,
                NEW.factor_unit, NEW.co2e_unit, NEW.source_name, NEW.source_url,
                NEW.source_year, NEW.region
            ) IS DISTINCT FROM ROW(
                OLD.id, OLD.created_at, OLD.category, OLD.activity_type, OLD.factor_value,
                OLD.factor_unit, OLD.co2e_unit, OLD.source_name, OLD.source_url,
                OLD.source_year, OLD.region
            ) THEN
                RAISE EXCEPTION 'Emission factor values and provenance are immutable';
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER trg_emission_factors_immutable
        BEFORE UPDATE OR DELETE ON emission_factors
        FOR EACH ROW EXECUTE FUNCTION prevent_emission_factor_rewrite();
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TRIGGER IF EXISTS trg_emission_factors_immutable ON emission_factors')
    op.execute('DROP FUNCTION IF EXISTS prevent_emission_factor_rewrite()')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_goals_user_id', table_name='goals')
    op.drop_table('goals')
    op.drop_index('ix_activities_user_id', table_name='activities')
    op.drop_index('ix_activities_emission_factor_id', table_name='activities')
    op.drop_index('ix_activities_category_id', table_name='activities')
    op.drop_index('ix_activities_activity_date', table_name='activities')
    op.drop_table('activities')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('emission_factors')
    op.drop_table('categories')
    # ### end Alembic commands ###